
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\tModLoader.targets" />
  <PropertyGroup>
    <AssemblyName>JustAQualityOfLife</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Localization\en-US.hjson" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
</Project>